apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.appSetName }}
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          dev: "True"
          prod: "True"
  template:
    metadata:
      name: '{{ .Values.projectName }}-{{ "{{ name }}" }}'
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/michaelkotelnikov/argocd-bench-list-generator.git'
          path: list-app-19
          targetRevision: master
          helm:
            valueFiles:
            - 'values.yaml'
            parameters:
              - name: global.clusterName
                value: '{{ "{{ name }}" }}'
        {{- /*
        - repoURL: https://github.com/DavidDaskalo/distributed-argocd-demo.git
          targetRevision: main
          path: environments/hotfix
          helm:
            valueFiles:
            - 'values.yaml'
            parameters:
              - name: global.clusterName
                value: '{{ "{{ metadata.name }}" }}'
        - repoURL: https://github.com/DavidDaskalo/distributed-argocd-demo.git
          targetRevision: main
          path: environments/prod
          helm:
            valueFiles:
            - 'values.yaml'
            parameters:
              - name: global.clusterName
                value: '{{ "{{ metadata.name }}" }}'
          */}}
      destination:
        name: 'in-cluster'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true