apiVersion: argoproj.io/v1alpha1
kind: ApplicationSeprodt
metadata:
  name: {{ .Values.appSetName }}
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          test: prod
  template:
    metadata:
      name: '{{ .Values.projectName }}-{{ "metadata.labels.<key>"  }}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/DavidDaskalo/distributed-argocd-demo.git
          targetRevision: main
          path: environments/prod
          helm:
            valueFiles:
            - 'values.yaml'
            parameters:
              - name: global.clusterName
                value: '{{ metadata.labels.<key> }}'
        {{- /*
        - repoURL: https://github.com/DavidDaskalo/distributed-argocd-demo.git
          targetRevision: main
          path: environments/hotfix
          helm:
            valueFiles:
            - 'values.yaml'
            parameters:
              - name: global.clusterName
                value: '{{ metadata.labels.<key> }}'
        - repoURL: https://github.com/DavidDaskalo/distributed-argocd-demo.git
          targetRevision: main
          path: environments/dev
          helm:
            valueFiles:
            - 'values.yaml'
            parameters:
              - name: global.clusterName
                value: '{{ metadata.labels.<key> }}'
          */}}
      destination:
        name: 'in-cluster'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true