apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-to-argo-{{ template "cluster_name" . }}
  namespace: {{ .Values.argocdNamespace }}
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: https://kubernetes.default.svc
  project: {{ .Values.spec.project }}
  source:
    path: edge-app/
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
