apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web-route
spec:
  host: "demo-app.apps.{{ template "cluster_name" . }}.cloudlet-dev.com"
  path: "/"
  to:
    kind: Service
    name: web-loadbalancer
