apiVersion: v1
kind: Service
metadata:
  name: web-loadbalancer
  namespace: demo-app
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
  selector:
    app: web-app

